# Generated by Django 5.1.3 on 2024-12-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_recipeingredient_measurement_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('entree', 'Entree'), ('dessert', 'Dessert')], default='entree', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
